[profile.default]
src = "contracts"
solc = "0.8.25"

evm_version = "cancun"

remappings = [
	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
	'@eth-optimism=lib/optimism/packages/',
]

optimizer = true
optimizer_runs = 200
