name = "op-gateway-worker"
main = "./src/worker.ts"
node_compat = true
compatibility_date = "2023-10-13"

[dev]
port = 8080

[build]
command = "bun run build"

[env.base-sepolia]
name = "base-sepolia-gateway-worker"
[env.base-sepolia.vars]
GATEWAY_DOMAIN="base-sepolia-gateway-worker.ens-cf.workers.dev"
[env.op-sepolia]
name = "op-sepolia-gateway-worker"
[env.op-sepolia.vars]
GATEWAY_DOMAIN="op-sepolia-gateway-worker.ens-cf.workers.dev"